name: frontend CI/CD
on:
  push:
    paths:
      - "frontend/**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  frontend-CI-CD:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch # 해당 레포 CI환경으로 클론
        uses: actions/checkout@v4

      - name: Node.js 18.x Version # Node 설치
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Build ## npm, init,build
        run: |
          echo ${{ secrets.MAIN_ENV }} | base64 -d > .env.production
          npm install
          npm run build
          npm run export
        # npm run lint
        working-directory: frontend

      - name: Configure AWS credentials
        if: ${{ github.ref == 'refs/heads/main' }} # 현재 브랜치가 main일때만 실행
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to Main S3 and Invalidate CloudFront cache
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          cd frontend
          aws s3 sync ./dist s3://${{ secrets.AWS_S3_CLIENT_MAIN_BUCKET_NAME }}
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_MAIN_DISTRIBUTION_ID }} --paths "/*"
